In [ ]:
import pandas as pd

In [ ]:
ppkm = pd.read_csv("ppkm_all.csv")
ppkm.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,29,30,31,34,35) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,Unnamed: 0.1,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,...,user_location,user_name,user_screen_name.1,user_statuses_count,user_time_zone,user_urls,user_verified,quote_id,retweet_id,user_id
0,0,0,NaN,Thu Jan 07 01:24:25 +0000 2021,NaN,NaN,NaN,0,1.346991e+18,NaN,...,"Depok, Jawa Barat",Muhammad Iqbal,eijkball,49200.0,NaN,NaN,False,NaN,NaN,NaN
1,1,1,NaN,Thu Jan 07 02:50:23 +0000 2021,NaN,NaN,https://www.tribunnews.com/corona/2021/01/07/b...,0,1.347013e+18,NaN,...,Indonesia,Tribunnews,tribunnews,746731.0,NaN,http://www.tribunnews.com,False,NaN,NaN,NaN
2,2,2,NaN,Thu Jan 07 03:20:33 +0000 2021,NaN,NaN,https://kabar24.bisnis.com/read/20210107/15/13...,3,1.347020e+18,NaN,...,"Jakarta, Indonesia",Bisnis.com,Bisniscom,1252831.0,NaN,http://www.bisnis.com,True,NaN,NaN,NaN
3,3,3,NaN,Thu Jan 07 03:39:03 +0000 2021,NaN,NaN,NaN,0,1.347025e+18,NaN,...,NaN,Wahyu Subarkah,wa_subarkah,2262.0,NaN,NaN,False,NaN,NaN,NaN
4,4,4,NaN,Thu Jan 07 03:41:26 +0000 2021,NaN,NaN,NaN,0,1.347026e+18,NaN,...,"Depok, Jawa Barat",Edwin Bachtiar Simandjoentak,dwinjoentak,20018.0,NaN,NaN,False,NaN,NaN,NaN

In [ ]:
ppkm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3077237 entries, 0 to 3077236
Data columns (total 39 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Unnamed: 0                  object
 1   Unnamed: 0.1                object
 2   coordinates                 object
 3   created_at                  object
 4   hashtags                    object
 5   media                       object
 6   urls                        object
 7   favorite_count              object
 8   id                          float64
 9   in_reply_to_screen_name     object
 10  in_reply_to_status_id       object
 11  in_reply_to_user_id         object
 12  lang                        object
 13  place                       object
 14  possibly_sensitive          object
 15  retweet_count               object
 16  reweet_id                   object
 17  retweet_screen_name         object
 18  source                      object
 19  text                        object
 20  tweet_url                   object
 21  user_created_at             object
 22  user_screen_name            object
 23  user_default_profile_image  object
 24  user_description            object
 25  user_favourites_count       float64
 26  user_followers_count        float64
 27  user_friends_count          float64
 28  user_listed_count           float64
 29  user_location               object
 30  user_name                   object
 31  user_screen_name.1          object
 32  user_statuses_count         float64
 33  user_time_zone              float64
 34  user_urls                   object
 35  user_verified               object
 36  quote_id                    float64
 37  retweet_id                  float64
 38  user_id                     float64
dtypes: float64(10), object(29)
memory usage: 915.6+ MB

## Data Preprocessing

1. Data to be processed is username twitter, real name user, reply to who (username) and tweet.

In [ ]:
data_user = ppkm[['user_screen_name', 'user_description', 'user_followers_count', 'user_location', 'user_name', 'user_urls','in_reply_to_screen_name', 'text']]
data_user

,user_screen_name,user_description,user_followers_count,user_location,user_name,user_urls,in_reply_to_screen_name,text
0,eijkball,Pewarta,877.0,"Depok, Jawa Barat",Muhammad Iqbal,NaN,NaN,jadi istilahnya pemberlakuan pembatasan kegiat...
1,tribunnews,Twitter resmi https://t.co/rPOl9T6Yb5.\nDownlo...,1157740.0,Indonesia,Tribunnews,http://www.tribunnews.com,NaN,berapa lonjakan kasus covid-19 yang buat pemer...
2,Bisniscom,"Akun resmi https://t.co/smhwo8PoSD. Berita, an...",1071328.0,"Jakarta, Indonesia",Bisnis.com,http://www.bisnis.com,NaN,"bukan psbb, pemerintah terapkan ppkm di jawa-b..."
3,wa_subarkah,An ordinary man. Not an idol worshipper.,49.0,NaN,Wahyu Subarkah,NaN,NaN,karantina wilayah ❎\npsbb ❎ (punya anies)\nppk...
4,dwinjoentak,"Semoga yang Disemogakan segera Tersemogakan, @...",214.0,"Depok, Jawa Barat",Edwin Bachtiar Simandjoentak,NaN,NaN,(psbb - psbmk - ppkm) cara indonesia menghadap...
...,...,...,...,...,...,...,...,...
3077232,Fhitrie82594485,Indonesia kuat,66.0,NaN,Fhitrie,NaN,Fhitrie82594485,pemerintah telah melakukan pelanggaran kebijak...
3077233,Anggalihma1994,Pada akhirnya kehormatan memang selalu datang ...,2386.0,Indonesia,Angga,NaN,NaN,"yang harus dinikmati kopi pahit nya, bukan jan..."
3077234,Info_dari_Anda,Platform distribusi berita dan konten bagi pro...,1641.0,Indonesia,Info dari Anda,http://infodarianda.com,NaN,polisi door-to-door bantu lansia suntik vaksin...
3077235,polreslahat,🇮🇩Akun resmi Humas Polres Lahat\nAKBP EKO SUMA...,572.0,Mapolres Lahat,Humas_polreslahat,http://tribratanews.lahat.sumsel.polri.go.id,NaN,ingat 5m selama pandemi ya temen-temen!\nmari ...
3077236,polreslahat,🇮🇩Akun resmi Humas Polres Lahat\nAKBP EKO SUMA...,572.0,Mapolres Lahat,Humas_polreslahat,http://tribratanews.lahat.sumsel.polri.go.id,NaN,humas polres lahat - giat vaksinasi sekira 08...

2. We only use "real people" username twitter, not the organization or business account. But, in this case, we are not using account detection to separate it, we only detect from url column, if account has url, it indicates the account is organization or business account.

In [ ]:
data_user = data_user[data_user['user_urls'].isna()]

In [ ]:
data_user.drop(['user_urls'], axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

3. Check bot account with followers, description and location. The real account is account has big follower with description and location. (This is not really accurate)

In [ ]:
data_user = data_user.drop(data_user[(data_user.user_followers_count < 1000)].index) 
data_user

,user_screen_name,user_description,user_followers_count,user_location,user_name,in_reply_to_screen_name,text
12,iyajgybg,iyajgybg,2100.0,NaN,iyajgybg,NaN,psbb❌\nppkm❌\npkp pecheneg✅ https://t.co/n5day...
13,RustamIbrahim,"This twitter is dedicated to voter education, ...",24338.0,Jakarta,Voter Education,NaN,1) tentu kita setuju saja dengan pengawasan pr...
15,Anjaswisesa_K,SUATU SAAT NANTI AKU AKAN MENJADI SEORANG HOKA...,1226.0,"Lampung, Indonesia",ANJAS WISESA,kumparan,@kumparan kalo liat berita luar negeri namanya...
33,mhsgunadarma,Penuh ke-salty-an khas anak Gunadarma 👌\n| Ins...,3876.0,"Depok, Jawa Barat",IG : Mahasiswagunadarma,NaN,pemberlakuan pembatasan kegiatan masyarakat al...
36,itsme_ini,Akun receh aku tuh kakaak...cuek tapi setia lh...,4492.0,NaN,Its♍_ajalah,NaN,ppkm... apalagi sih...gonta ganti istilah mulu...
...,...,...,...,...,...,...,...
3077201,bhineka_indo,Keseimbangan diperlukan dalam kehidupan🇮🇩🇮🇩\nK...,1591.0,NaN,KETUYUT🇮🇩,NaN,penerapan ppkm untuk mengendalikan laju penyeb...
3077202,bhineka_indo,Keseimbangan diperlukan dalam kehidupan🇮🇩🇮🇩\nK...,1591.0,NaN,KETUYUT🇮🇩,NaN,"sukses tekan angka kasus harian, ppkm jadikan ..."
3077220,cienfleurwings,NaN,1248.0,NaN,acltair,Mantanmunih,"@mantanmunih @jogmfs bener, kelamaan ppkm maka..."
3077225,ariestarico2,|| penyuka kopi || Anti rasis || no modus ||,7736.0,🇲🇨peace,Riest,crnnamon,@iecstyling dukung ppkm
3077233,Anggalihma1994,Pada akhirnya kehormatan memang selalu datang ...,2386.0,Indonesia,Angga,NaN,"yang harus dinikmati kopi pahit nya, bukan jan..."

In [ ]:
data_user = data_user[data_user['user_description'].notna()]
data_user = data_user[data_user['user_location'].notna()]

In [ ]:
data_user = data_user[['user_screen_name', 'user_name','in_reply_to_screen_name', 'text']]
data_user

,user_screen_name,user_name,in_reply_to_screen_name,text
13,RustamIbrahim,Voter Education,NaN,1) tentu kita setuju saja dengan pengawasan pr...
15,Anjaswisesa_K,ANJAS WISESA,kumparan,@kumparan kalo liat berita luar negeri namanya...
33,mhsgunadarma,IG : Mahasiswagunadarma,NaN,pemberlakuan pembatasan kegiatan masyarakat al...
39,KATADATAcoid,Katadata.co.id,NaN,ketua satuan tugas penanganan covid-19 doni mo...
46,Beritasatu,BeritaSatu,NaN,menko perekonomian tegaskan ppkm berbeda denga...
...,...,...,...,...
3077194,P3rsada27,🅿🅴🆁🆂🅰🅳🅰 👉🏻2⃣7⃣🇲🇨,NaN,"kasus covid-19 melandai berkat penerapan ppkm,..."
3077195,P3rsada27,🅿🅴🆁🆂🅰🅳🅰 👉🏻2⃣7⃣🇲🇨,NaN,penerapan ppkm untuk mengendalikan laju covid-...
3077198,KangSemproel,Hilik Ku Aink Wae Lah✌,mapunk121,@mapunk121 @endridok itu mah pengalaman adek g...
3077225,ariestarico2,Riest,crnnamon,@iecstyling dukung ppkm
3077233,Anggalihma1994,Angga,NaN,"yang harus dinikmati kopi pahit nya, bukan jan..."

4. Remove duplicate data user

In [ ]:
data_user_unique = data_user[["user_screen_name","user_name"]]

In [ ]:
data_user_unique[data_user_unique["user_screen_name"].duplicated()]

        user_screen_name                user_name
159         mhsgunadarma  IG : Mahasiswagunadarma
166         KATADATAcoid           Katadata.co.id
172          JatengOpini             Jateng Opini
312                Azmfz               Azmi Fauzi
388         KATADATAcoid           Katadata.co.id
...                  ...                      ...
3077194        P3rsada27         🅿🅴🆁🆂🅰🅳🅰 👉🏻2⃣7⃣🇲🇨
3077195        P3rsada27         🅿🅴🆁🆂🅰🅳🅰 👉🏻2⃣7⃣🇲🇨
3077198     KangSemproel   Hilik Ku Aink Wae Lah✌
3077225     ariestarico2                   Riest
3077233   Anggalihma1994                    Angga

[73706 rows x 2 columns]

In [ ]:
data_user_unique.drop_duplicates(subset=['user_screen_name'],inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [ ]:
data_user_unique.to_csv("master_data_user.csv")
!cp master_data_user.csv "drive/My Drive/Data Science Project"

In [ ]:
data_user_text = data_user[["user_screen_name","text"]]

In [ ]:
data_user.to_csv("data_user_cleaned_with_user_text_only.csv")
!cp data_user_cleaned_with_user_text_only.csv "drive/My Drive/Data Science Project"